---
output: 
  html_document:
    toc: true
    toc_float: true
---

# Juliann McEachern 

Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb Blerb


## Education

### CUNY MSDS

text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text

### UMASS Amherst

text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text

## Experience

### Job 1 
text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text

### Job 2
text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text

### Job 3
text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text


## Skills

text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text text
